openapi: 3.0.2
info:
  version: 1.0.0
  title: IT SYNC API Service
  description: 'IT SYNC Service API Specification.'

servers:
  - url: /api/v1

tags:
  - name: IT SYNC Web
    description: "API for IT SYNC"

paths:

  /books/getAllBooks:
    get:
      tags:
        - books
      summary: "Retrieve all markets"
      operationId: getAllBooks
      x-operationId-exception: true
      parameters:
        - in: query
          explode: false
          name: bookId
          required: false
          schema:
            type: string
      x-spring-paginated: true
      responses:
        200:
          description: "List of All books"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"


components:
  parameters:
    AuditUserIdHeader:
      name: X-loggedInUserId
      description: loggedInUserId for audit
      in: header
      required: true
      schema:
        type: integer

    PageNumber:
      in: query
      name: page
      description: "Page Number to return"
      required: true
      schema:
        type: integer
        default: 0
        example: 1

    PageSize:
      in: query
      name: size
      description: "Number of results in a page"
      required: true
      schema:
        type: integer
        default: 20
        example: 10
        maximum: 50

  responses:
    500ApiError:
      description: "There is Unexpected 500 error."
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: string
                example: 500
              message:
                type: string
                example: "This is a 500 error"

  schemas:
    Response:
      type: object
      properties:
        data:
          type: object
        totalItems:
          type: integer
          format: int64
        _links:
          $ref: '#/components/schemas/_links'

    _link:
      type: object
      properties:
        href:
          type: string

    _links:
      type: array
      items:
        $ref: '#/components/schemas/_link'

    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          description: Title of the book
        author:
          type: string
          description: Author of the book
        price:
          type: number
          description: Price of the book
          format: double
      required:
        - title
        - author
        - price